# Generated by Django 5.2.16 on 2026-07-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('name_fa', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_fa', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Price in IRR (toman-style integer)')),
                ('compare_at_price', models.PositiveIntegerField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=80)),
                ('color_hex', models.CharField(default='#682050', max_length=7)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['color', 'size'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
